services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: distcomp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "24110:24110"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/distcomp
    depends_on:
      db:
        condition: service_healthy
