spring:
  application:
    name: distributed_computing
  datasource:
    url: 'jdbc:postgresql://localhost:5432/distcomp'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  kafka:
    topics:
      notice:
        in: InTopic
        out: OutTopic
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      bootstrap-servers: "localhost:9092"

server:
  port: 24110
  servlet:
    context-path: /api/v1.0

discussion:
  address: http://localhost:24130
  baseApiPath: /api/v1.0
