// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskSQL.Storage;

#nullable disable

namespace TaskSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagTweet", b =>
                {
                    b.Property<long>("Tagsid")
                        .HasColumnType("bigint");

                    b.Property<long>("Tweetsid")
                        .HasColumnType("bigint");

                    b.HasKey("Tagsid", "Tweetsid");

                    b.HasIndex("Tweetsid");

                    b.ToTable("TagTweet");
                });

            modelBuilder.Entity("TaskSQL.Models.Creator", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("tbl_creator");
                });

            modelBuilder.Entity("TaskSQL.Models.Notice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("Tweetid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("Tweetid");

                    b.ToTable("tbl_notice");
                });

            modelBuilder.Entity("TaskSQL.Models.Tag", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_tag");
                });

            modelBuilder.Entity("TaskSQL.Models.Tweet", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("creator_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("id");

                    b.HasIndex("creator_id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("tbl_tweet");
                });

            modelBuilder.Entity("TagTweet", b =>
                {
                    b.HasOne("TaskSQL.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tagsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSQL.Models.Tweet", null)
                        .WithMany()
                        .HasForeignKey("Tweetsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskSQL.Models.Notice", b =>
                {
                    b.HasOne("TaskSQL.Models.Tweet", "Tweet")
                        .WithMany("Notice")
                        .HasForeignKey("Tweetid");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("TaskSQL.Models.Tweet", b =>
                {
                    b.HasOne("TaskSQL.Models.Creator", "Creator")
                        .WithMany("Tweets")
                        .HasForeignKey("creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TaskSQL.Models.Creator", b =>
                {
                    b.Navigation("Tweets");
                });

            modelBuilder.Entity("TaskSQL.Models.Tweet", b =>
                {
                    b.Navigation("Notice");
                });
#pragma warning restore 612, 618
        }
    }
}
