// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lab2_jpa;

#nullable disable

namespace lab2_jpa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.Property<long>("Articlesid")
                        .HasColumnType("bigint");

                    b.Property<long>("Tagsid")
                        .HasColumnType("bigint");

                    b.HasKey("Articlesid", "Tagsid");

                    b.HasIndex("Tagsid");

                    b.ToTable("ArticleTag");
                });

            modelBuilder.Entity("lab2_jpa.Models.Article", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("creator_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("creator_id");

                    b.ToTable("tbl_article");
                });

            modelBuilder.Entity("lab2_jpa.Models.Creator", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("tbl_creator");
                });

            modelBuilder.Entity("lab2_jpa.Models.Note", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("Articleid")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("id");

                    b.HasIndex("Articleid");

                    b.ToTable("tbl_note");
                });

            modelBuilder.Entity("lab2_jpa.Models.Tag", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_tag");
                });

            modelBuilder.Entity("ArticleTag", b =>
                {
                    b.HasOne("lab2_jpa.Models.Article", null)
                        .WithMany()
                        .HasForeignKey("Articlesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab2_jpa.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tagsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lab2_jpa.Models.Article", b =>
                {
                    b.HasOne("lab2_jpa.Models.Creator", "Creator")
                        .WithMany("Articles")
                        .HasForeignKey("creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("lab2_jpa.Models.Note", b =>
                {
                    b.HasOne("lab2_jpa.Models.Article", "Article")
                        .WithMany("Notes")
                        .HasForeignKey("Articleid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("lab2_jpa.Models.Article", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("lab2_jpa.Models.Creator", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
