build:
	docker build -t significantnose/social-net-publisher -f ./Publisher/Dockerfile .
	docker build -t significantnose/social-net-discussion -f ./Discussion/Dockerfile .

build-publisher:
	docker build -t significantnose/social-net-publisher -f ./Publisher/Dockerfile .

build-discussion:
	docker build -t significantnose/social-net-discussion -f ./Discussion/Dockerfile .
